baseURL = "https://philomusica.org.uk"
languageCode = "en-gb"
title = "Philomusica"
theme = "philo-hugo-theme"
uglyurls = true
[params]
include_home_in_menu = true
call_to_action_text = "Come and Sing"
Description = "Website of mixed voice choir Philomusica; based in Gloucestershire & Worcestershire we are the best and friendliest choir around."
SiteImage = "/img/logo.jpg"
RecaptchaKey = "6LfSfwgeAAAAAEp44z7X9pMojMP0gtA0pc2nQTXS"
# If uglyurls is set to true, link need to be suffixed with .html
caLl_to_action_link = "/sing.html"
[markup.goldmark.renderer]
unsafe= true
