baseURL = "https://philomusica.org.uk"
languageCode = "en-us"
title = "Philomusica"
theme = "philo-hugo-theme"
[params]
callToActionText = "Tickets"
callToActionLink = "http://192.168.1.103:1313/tickets"
